name: Generate a changelog
description: Wraps lerna-changelog to generate a changelog between two commits or tags
author: 'Matt Turner'

inputs:
  old:
    description: Old ref
  new:
    description: New ref

outputs:
  changelog:
    description: Changelog formatted as a JSON string

runs:
  using: node12
  main: 'dist/index.js'

branding:
  icon: file-text
  color: green
